### ISSUE TITLE
Canvas is loading empty 

### ISSUE THREAD

**Issue by SamkitSanghvi** [Foblex/f-scheme-editor#1]
![Screenshot 2024-11-06 140431](https://github.com/user-attachments/assets/15409009-30b5-4b46-a6bc-a76f0c9eba09)
Not getting the item on the left-side panel to drop on the canvas

**Comment by siarheihuzarevich** [comment]
Create item using right mouse button

**Comment by SamkitSanghvi** [comment]
with the right-click I have created a schema drawer
after that how to create a group and 
can you just give me detailed steps to render the node on the canvas

**Comment by siarheihuzarevich** [comment]
@SamkitSanghvi this is just an example of using the library, not a ready-made editor. what made you think that you can create groups here. Please read the description carefully

**Comment by SamkitSanghvi** [comment]
Ohh
I thought I can playaround with the demo
same as the call-center DEMO

**Comment by siarheihuzarevich** [comment]
Yes, you can add nodes to canvas, customize its and etc
